# cloudbuild.yaml — fixed for REGIONAL_USER_OWNED_BUCKET handling
substitutions:
  _ARTIFACT_REPO: "asia-southeast1-docker.pkg.dev/$PROJECT_ID/github2cloudrun-nextjs"
  _IMAGE_NAME: "${_ARTIFACT_REPO}/testing-ci-cd"
  _LOGS_BUCKET: "gs://cloud-build-logs-oneject-service-asia-southeast1" # buat referensi, tidak dipakai langsung here
  _REGION: "asia-southeast1"
  _SERVICE: "testing-ci-cd"

options:
  # gunakan behavior yang didukung agar sesuai org policy user-owned logs
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"
  logging: "CLOUD_LOGGING_ONLY"
  machineType: E2_SMALL

steps:
  - name: "node:18"
    id: "install-and-test"
    entrypoint: bash
    args:
      - -c
      - |
        npm ci
        npm test || (echo "Tests failed" && exit 1)
        npm run build

  - name: "gcr.io/kaniko-project/executor:latest"
    id: "build-and-push"
    args:
      - --dockerfile=Dockerfile
      - --context=dir://.
      - --destination=${_IMAGE_NAME}:${SHORT_SHA}
      - --destination=${_IMAGE_NAME}:latest
    env:
      - "DOCKER_CONFIG=/kaniko/.docker/"

  - name: "anchore/syft:latest"
    id: "generate-sbom"
    entrypoint: /bin/sh
    args:
      - -c
      - |
        syft ${_IMAGE_NAME}:${SHORT_SHA} -o cyclonedx-json > sbom.cdx.json || syft dir:. -o cyclonedx-json > sbom.cdx.json
    waitFor: ["build-and-push"]

  - name: "aquasec/trivy:latest"
    id: "trivy-scan"
    entrypoint: /bin/sh
    args:
      - -c
      - |
        trivy image --severity CRITICAL,HIGH --exit-code 1 ${_IMAGE_NAME}:${SHORT_SHA} || { echo "Vulnerabilities found"; exit 1; }
    waitFor: ["build-and-push", "generate-sbom"]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-to-cloud-run"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" ]]; then
          IMAGE=${_IMAGE_NAME}:${SHORT_SHA}
          gcloud run deploy ${_SERVICE} \
            --image=$IMAGE \
            --platform=managed \
            --region=${_REGION} \
            --allow-unauthenticated \
            --quiet
        else
          echo "Not main/master branch ($BRANCH_NAME) - skipping deploy"
        fi

artifacts:
  objects:
    location: "gs://$PROJECT_ID-cloudbuild-artifacts/sbom/${SHORT_SHA}/"
    paths: ["sbom.cdx.json"]
